Update test_env_override.yml

diff --git a/.github/workflows/test_env_override.yml b/.github/workflows/test_env_override.yml
--- a/.github/workflows/test_env_override.yml
+++ b/.github/workflows/test_env_override.yml
@@ -5,8 +5,15 @@ on: workflow_dispatch
 jobs:
   greeting_job:
     runs-on: ubuntu-24.04
+    env:
+      NDK_VERSION: 28.2.13676358
     steps:
-      
-      - name: "Log envs"
+      - name: Configure android ndk
         run: |
-          find $ANDROID_NDK_HOME 
+          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/$NDK_VERSION" >> $GITHUB_ENV
+          if [ -d "ANDROID_NDK_HOME" ]; then
+            echo "Using ndk $ANDROID_NDK_HOME"
+          else
+            echo "$ANDROID_NDK_HOME not found, abort."
+            exit 1
+          fi    
